version: '3.0'
services:
  unite1:
    build: unite
    #ports:
    #- "9000:9000"
    volumes:
    - data:/src/data
    entrypoint: /start.sh 1 9001
    depends_on:
    - collecteur
  unite2:
    build: unite
    volumes:
    - data:/src/data
    entrypoint: /start.sh 2 9002
    depends_on:
    - collecteur
  back:
    build: back
    ports:
    - "5000:5000"
    depends_on:
    - db
  collecteur:
    build: collecteur
    ports:
    - "1111:1111"
    depends_on:
    - db
  front:
    build: front
    ports:
    - "8080:80"
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: 'devops'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - '3306:3306'
    expose:
        - '3306'
    volumes:
        - ./ynov_devops.sql:/docker-entrypoint-initdb.d/dump.sql
        - my-db:/var/lib/mysql
volumes:
  data: {}
  my-db: {}